### PR TITLE
Resolves "Fix searching subscription leads to memory leak""

### LINKED ISSUE #453: Cannot read property 'length' of null
https://sentry.io/organizations/savand-bros-cx/issues/1668572045/?project=1886804&query=is%3Aunresolved

### PR DESCRIPTION
**Pull request by ArsalanSavand**
Fixes #453

### CODE REVIEW

File: src/app/components/feed/reader/reader.component.ts [hunk 1]
```diff
@@ -64,4 +72,8 @@ export class ReaderComponent implements OnInit {
       this.feed.getEntries({ show, search }).subscribe(onLoadEntries);
     });
   }
+
+  ngOnDestroy() {
```
Comment (Alir3z4) [inline src/app/components/feed/reader/reader.component.ts:76]:
```suggestion
  ngOnDestroy(): void {
```
