### PR TITLE
Resolves "Fix profile page at feed having memory leak which leads to running code after page has been destroyed"

### LINKED ISSUE #463: Fix profile page at feed having memory leak which leads to running code after page has been destroyed

### PR DESCRIPTION
**Pull request by ArsalanSavand**
Fixes #463

### CODE REVIEW

File: src/app/components/feed/user/user.component.ts [hunk 1]
```diff
@@ -62,38 +69,42 @@ export class UserComponent implements OnInit, OnDestroy {
...
-    this.router.events.pipe(untilComponentDestroyed(this)).subscribe((event: RouterEvent): void => {
-      if (!(event instanceof NavigationEnd)) {
-        return;
-      }
-      document.getElementsByClassName('feed-scroller')[0].scrollTo(0, 0);
-    });
+    this.subscription.add(
+      this.router.events.subscribe((event: RouterEvent): void => {
+        if (!(event instanceof NavigationEnd)) {
+          return;
```
Comment (Alir3z4) [inline src/app/components/feed/user/user.component.ts:75]: Would be great to a have a comment in here explaining why it's returning none.
