### PR TITLE
Resolves "Fix editor's update buttons and behaviors for better UX"

### LINKED ISSUE #468: Prevent editor from making actions when it's not yet initialized
https://sentry.io/organizations/savand-bros-cx/issues/1700809035/?project=1886804&query=is%3Aunresolved

### LINKED ISSUE #469: Fix editor's update buttons and behaviors for better UX

### PR DESCRIPTION
**Pull request by ArsalanSavand**
Closes #469 
Closes #468 

image

image

### CODE REVIEW

File: src/app/components/dash/write/write.component.ts [hunk 1]
```diff
@@ -1315,7 +1336,10 @@ export class WriteComponent implements OnInit, AfterViewInit, OnDestroy {
    * @param range Range
    */
   setBubblePosition(element: HTMLElement, range: RangeStatic): void {
-    if (!range) {
+    /**
+     * Prevent code from running if the editor is not yet initialized or given range is invalid.
```
Comment (Alir3z4) [inline src/app/components/dash/write/write.component.ts:1340]: Should not be annotated with multi line commenting

File: src/app/components/dash/write/write.component.ts [hunk 2]
```diff
@@ -1597,17 +1624,53 @@ export class WriteComponent implements OnInit, AfterViewInit, OnDestroy {
...
+  }
+
   /**
    * Save entry
    *
    * @param status Status of entry
    */
   save(status?: EntryStatus): void {
+    /**
+     * Setup payload and required fields.
```
Comment (Alir3z4) [inline src/app/components/dash/write/write.component.ts:1664]: Should not be annotated with multi line commenting

File: src/app/components/dash/write/write.component.ts [hunk 3]
```diff
@@ -1617,9 +1680,9 @@ export class WriteComponent implements OnInit, AfterViewInit, OnDestroy {
       payload.start_publication = null;
     }
     /**
-     * Check status before updating
+     * If method was called with auto save in progress, then remove `status` property from payload to save entrydraft.
      */
-    if (this.autoSave) {
+    if (this.autoSave || status === null) {
```
Comment (Alir3z4) [inline src/app/components/dash/write/write.component.ts:1685]: some documentation and reasons behind this condition would be good.

File: src/app/components/dash/write/write.component.ts [hunk 4]
```diff
@@ -1629,32 +1692,27 @@ export class WriteComponent implements OnInit, AfterViewInit, OnDestroy {
...
-        this.form.updateValueAndValidity();
-      }
-    }, (): void => {
-      this.loading = false;
-    });
+  setStatus(status: EntryStatus): void {
+    /**
+     * It's being used to display confirm message based on given entry status from param.
+     */
+    let confirmMessage = 'PUBLISH_ENTRY_CONFIRM';
```
Comment (Alir3z4) [inline src/app/components/dash/write/write.component.ts:1705]: Better to have this in the `else` condition of the following if condition.

File: src/app/components/dash/write/write.component.ts [hunk 5]
```diff
@@ -1629,32 +1692,27 @@ export class WriteComponent implements OnInit, AfterViewInit, OnDestroy {
...
+    if (status === EntryStatus.Draft) {
+      confirmMessage = 'DRAFT_ENTRY_CONFIRM';
+    }
+    /**
+     * Prompt a native confirm alert to ask the user to change status.
```
Comment (Alir3z4) [inline src/app/components/dash/write/write.component.ts:1710]: Should not be annotated with multi line commenting
